# Generated by Django 5.2.12 on 2026-07-27 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_membership_practitioner'),
        ('scheduling', '0008_remap_waiting_status'),
        ('tenants', '0004_clinic_appointments_backfilled_until'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='membership',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('practitioner__isnull', False)), fields=('clinic', 'practitioner'), name='uniq_membership_clinic_practitioner'),
        ),
    ]
