# Generated by Django 5.2.12 on 2026-07-30 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_membership_uniq_membership_clinic_practitioner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='role',
            field=models.CharField(choices=[('manager', 'Gestor'), ('doctor', 'Médico'), ('attendant', 'Atendente'), ('partner', 'Parceiro')], max_length=20, verbose_name='Papel'),
        ),
    ]
