# Generated by Django 5.2.12 on 2026-08-20 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_membership_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='must_change_password',
            field=models.BooleanField(default=False, help_text='Senha temporária em vigor (RF-EQP-7). Enquanto ligado, a API recusa toda rota que não seja trocar a senha, ver o perfil ou sair.', verbose_name='Precisa trocar a senha'),
        ),
        migrations.AddField(
            model_name='user',
            name='password_changed_at',
            field=models.DateTimeField(blank=True, help_text='Invalida token emitido ANTES dele (RF-CTA-3), no HTTP e no WebSocket. Sem este carimbo o refresh de 30 dias sobrevive à troca de senha e à revogação do vínculo, e quem saiu da clínica continua entrando pelo navegador já aberto.', null=True, verbose_name='Senha trocada em'),
        ),
    ]
