# Generated by Django 5.2.12 on 2026-07-09 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deletado em')),
                ('kind', models.CharField(choices=[('patients_full', 'Pacientes (completo)'), ('patients_delta', 'Pacientes (incremental)'), ('appointments', 'Agenda'), ('tags', 'Tags'), ('catalogs', 'Catálogos'), ('medical_records', 'Prontuário')], max_length=20, verbose_name='Tipo')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Início')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Fim')),
                ('stats', models.JSONField(blank=True, default=dict, help_text='Ex.: {"fetched": 120, "created": 3, "updated": 5}', verbose_name='Estatísticas')),
                ('error', models.TextField(blank=True, verbose_name='Erro')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)ss', to='tenants.clinic', verbose_name='Clínica')),
            ],
            options={
                'verbose_name': 'Execução de sync',
                'verbose_name_plural': 'Execuções de sync',
            },
        ),
        migrations.CreateModel(
            name='SyncOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deletado em')),
                ('provider', models.CharField(choices=[('vsaude', 'vSaúde')], max_length=20, verbose_name='Provedor')),
                ('direction', models.CharField(choices=[('push', 'Push (nós → EHR)')], default='push', max_length=10, verbose_name='Direção')),
                ('resource_type', models.CharField(choices=[('patient', 'Paciente'), ('appointment', 'Consulta'), ('tag', 'Tag'), ('patient_tags', 'Tags do paciente')], max_length=20, verbose_name='Recurso')),
                ('local_id', models.BigIntegerField(verbose_name='ID local')),
                ('payload', models.JSONField(help_text='Formato NOSSO — o adapter desnormaliza na saída.', verbose_name='Payload')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('running', 'Executando'), ('success', 'Sucesso'), ('failed', 'Falhou')], default='pending', max_length=10, verbose_name='Status')),
                ('attempts', models.PositiveSmallIntegerField(default=0, verbose_name='Tentativas')),
                ('last_error', models.TextField(blank=True, verbose_name='Último erro')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)ss', to='tenants.clinic', verbose_name='Clínica')),
            ],
            options={
                'verbose_name': 'Operação de sync',
                'verbose_name_plural': 'Operações de sync',
                'indexes': [models.Index(fields=['status', 'created_at'], name='integration_status_53e13f_idx')],
            },
        ),
    ]
