# Generated by Django 5.2.12 on 2026-07-09 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='syncoperation',
            name='provider',
            field=models.CharField(choices=[('vsaude', 'vSaúde'), ('fake', 'Fake (desenvolvimento)')], max_length=20, verbose_name='Provedor'),
        ),
    ]
