# Generated by Django 5.2.12 on 2026-07-09 21:36

import apps.core.fields
import apps.inbox.models.channel
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0004_alter_patient_last_appointment_at'),
        ('tenants', '0002_clinic_active_window_days_alter_clinic_ehr_provider'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deletado em')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador do canal na URL do webhook.', unique=True, verbose_name='UUID público')),
                ('provider', models.CharField(choices=[('datafy', 'Datafy'), ('fake', 'Fake (desenvolvimento)')], default='datafy', max_length=20, verbose_name='Provedor')),
                ('phone_number_id', models.CharField(blank=True, max_length=32, verbose_name='Phone Number ID')),
                ('waba_id', models.CharField(blank=True, max_length=32, verbose_name='WABA ID')),
                ('display_number', models.CharField(blank=True, max_length=20, verbose_name='Número exibido')),
                ('credentials', apps.core.fields.EncryptedJSONField(default=dict, verbose_name='Credenciais')),
                ('webhook_secret', models.CharField(default=apps.inbox.models.channel.default_webhook_secret, max_length=64, verbose_name='Segredo do webhook')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)ss', to='tenants.clinic', verbose_name='Clínica')),
            ],
            options={
                'verbose_name': 'Canal',
                'verbose_name_plural': 'Canais',
            },
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deletado em')),
                ('last_message_preview', models.CharField(blank=True, max_length=200, verbose_name='Prévia')),
                ('last_message_at', models.DateTimeField(db_index=True, null=True, verbose_name='Última mensagem em')),
                ('last_inbound_at', models.DateTimeField(null=True, verbose_name='Último inbound em')),
                ('unread_count', models.PositiveIntegerField(default=0, verbose_name='Não lidas')),
                ('needs_agent', models.BooleanField(default=False, verbose_name='Aguardando atendente')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_conversations', to=settings.AUTH_USER_MODEL, verbose_name='Atribuída a')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='conversations', to='inbox.channel', verbose_name='Canal')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)ss', to='tenants.clinic', verbose_name='Clínica')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='conversations', to='patients.contact', verbose_name='Contato')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='patients.patient', verbose_name='Paciente')),
            ],
            options={
                'verbose_name': 'Conversa',
                'verbose_name_plural': 'Conversas',
            },
        ),
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deletado em')),
                ('provider_media_id', models.CharField(blank=True, max_length=128, verbose_name='Media ID (provedor)')),
                ('stored_file', models.FileField(blank=True, upload_to='wa-media/%Y/%m/', verbose_name='Arquivo')),
                ('mime_type', models.CharField(blank=True, max_length=100, verbose_name='MIME')),
                ('size_bytes', models.PositiveIntegerField(blank=True, null=True, verbose_name='Tamanho (bytes)')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)ss', to='tenants.clinic', verbose_name='Clínica')),
            ],
            options={
                'verbose_name': 'Mídia',
                'verbose_name_plural': 'Mídias',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deletado em')),
                ('provider_message_id', models.CharField(blank=True, max_length=128, verbose_name='wamid')),
                ('direction', models.CharField(choices=[('in', 'Recebida'), ('out', 'Enviada')], editable=False, max_length=3, verbose_name='Direção')),
                ('kind', models.CharField(choices=[('text', 'Texto'), ('image', 'Imagem'), ('audio', 'Áudio'), ('video', 'Vídeo'), ('document', 'Documento'), ('sticker', 'Figurinha'), ('location', 'Localização'), ('interactive', 'Interativa'), ('template', 'Template'), ('unsupported', 'Não suportado')], default='text', max_length=12, verbose_name='Tipo')),
                ('body', models.TextField(blank=True, verbose_name='Texto')),
                ('caption', models.TextField(blank=True, verbose_name='Legenda')),
                ('reply_to_provider_id', models.CharField(blank=True, max_length=128, verbose_name='Responde a (wamid)')),
                ('status', models.CharField(blank=True, choices=[('sent', 'Enviada'), ('delivered', 'Entregue'), ('read', 'Lida'), ('failed', 'Falhou')], max_length=10, verbose_name='Status')),
                ('sender_kind', models.CharField(choices=[('contact', 'Contato'), ('agent', 'Atendente'), ('bot', 'Automação')], max_length=8, verbose_name='Autor')),
                ('template_name', models.CharField(blank=True, max_length=120, verbose_name='Template')),
                ('wa_timestamp', models.DateTimeField(db_index=True, verbose_name='Horário WhatsApp')),
                ('raw_payload', models.JSONField(blank=True, default=dict, verbose_name='Payload cru')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)ss', to='tenants.clinic', verbose_name='Clínica')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='inbox.conversation', verbose_name='Conversa')),
                ('media', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='inbox.mediaasset', verbose_name='Mídia')),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_messages', to=settings.AUTH_USER_MODEL, verbose_name='Enviada por')),
            ],
            options={
                'verbose_name': 'Mensagem',
                'verbose_name_plural': 'Mensagens',
                'ordering': ['wa_timestamp'],
            },
        ),
        migrations.CreateModel(
            name='QuickReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deletado em')),
                ('label', models.CharField(max_length=60, verbose_name='Rótulo')),
                ('body', models.TextField(verbose_name='Texto')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)ss', to='tenants.clinic', verbose_name='Clínica')),
            ],
            options={
                'verbose_name': 'Resposta rápida',
                'verbose_name_plural': 'Respostas rápidas',
                'ordering': ['label'],
            },
        ),
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('datafy', 'Datafy (WhatsApp)'), ('asaas', 'Asaas (billing)')], max_length=20, verbose_name='Origem')),
                ('dedupe_key', models.CharField(blank=True, db_index=True, max_length=200, verbose_name='Chave de deduplicação')),
                ('payload', models.JSONField(verbose_name='Payload')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Recebido em')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Processado em')),
                ('error', models.TextField(blank=True, verbose_name='Erro')),
                ('clinic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webhook_events', to='tenants.clinic', verbose_name='Clínica')),
            ],
            options={
                'verbose_name': 'Evento de webhook',
                'verbose_name_plural': 'Eventos de webhook',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WhatsAppTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deletado em')),
                ('name', models.CharField(max_length=120, verbose_name='Nome')),
                ('language', models.CharField(default='pt_BR', max_length=10, verbose_name='Idioma')),
                ('category', models.CharField(blank=True, max_length=30, verbose_name='Categoria')),
                ('status', models.CharField(blank=True, max_length=20, verbose_name='Status')),
                ('components', models.JSONField(blank=True, default=list, verbose_name='Componentes')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)ss', to='tenants.clinic', verbose_name='Clínica')),
            ],
            options={
                'verbose_name': 'Template WhatsApp',
                'verbose_name_plural': 'Templates WhatsApp',
                'ordering': ['name'],
            },
        ),
        migrations.AddConstraint(
            model_name='channel',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('clinic',), name='one_channel_per_clinic'),
        ),
        migrations.AddConstraint(
            model_name='conversation',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('channel', 'contact'), name='uniq_conversation_channel_contact'),
        ),
        migrations.AddConstraint(
            model_name='message',
            constraint=models.UniqueConstraint(condition=models.Q(('provider_message_id', ''), _negated=True), fields=('clinic', 'provider_message_id'), name='uniq_message_wamid'),
        ),
        migrations.AddIndex(
            model_name='webhookevent',
            index=models.Index(fields=['source', 'created_at'], name='inbox_webho_source_59f16d_idx'),
        ),
        migrations.AddIndex(
            model_name='webhookevent',
            index=models.Index(fields=['clinic', 'processed_at'], name='inbox_webho_clinic__400763_idx'),
        ),
        migrations.AddConstraint(
            model_name='whatsapptemplate',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('clinic', 'name', 'language'), name='uniq_template'),
        ),
    ]
