# Generated by Django 5.2.12 on 2026-07-27 18:15
# Datafy → Meta Cloud API direta (§7, decisão de 27/07/2026).

from django.db import migrations, models


def datafy_becomes_meta(apps, schema_editor):
    """Canais 'datafy' viram 'meta' - o transporte mudou, o canal é o mesmo.

    Só existem em banco de dev (nenhuma clínica real conectou WhatsApp);
    WebhookEvent é imutável e NÃO se mexe - eventos antigos guardam o source
    da época."""
    Channel = apps.get_model("inbox", "Channel")
    Channel.objects.filter(provider="datafy").update(provider="meta")


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='provider',
            field=models.CharField(choices=[('meta', 'Meta Cloud API'), ('fake', 'Fake (desenvolvimento)')], default='meta', max_length=20, verbose_name='Provedor'),
        ),
        migrations.RunPython(datafy_becomes_meta, migrations.RunPython.noop),
    ]
