# Generated by Django 5.2.12 on 2026-07-27 18:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0002_alter_channel_provider'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='webhook_secret',
        ),
        migrations.AlterField(
            model_name='channel',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador público estável do canal.', unique=True, verbose_name='UUID público'),
        ),
        migrations.AlterField(
            model_name='webhookevent',
            name='source',
            field=models.CharField(choices=[('meta', 'Meta (WhatsApp)'), ('datafy', 'Datafy (WhatsApp, legado)'), ('asaas', 'Asaas (billing)')], max_length=20, verbose_name='Origem'),
        ),
    ]
