# Generated by Django 5.2.12 on 2026-07-27 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0003_remove_channel_webhook_secret_alter_channel_uuid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='status_error',
            field=models.TextField(blank=True, help_text='Preenchido quando FAILED: errors[] do webhook ou erro de envio. "Falhou" sem motivo não ajuda ninguém a agir.', verbose_name='Motivo da falha'),
        ),
    ]
