# Generated by Django 5.2.12 on 2026-07-28 19:52

import django.db.models.deletion
from django.db import migrations, models


def recepcao_por_clinica(apps, schema_editor):
    """
    A clínica nasce com o setor que ela de fato tem hoje (§4.3.1, RF-ATD-5).
    Semear aqui evita que o B2 precise decidir o que fazer com clínicas sem
    setor nenhum - e "Recepção" é o nome que a própria clínica usa.
    """
    Clinic = apps.get_model("tenants", "Clinic")
    Team = apps.get_model("inbox", "Team")
    for clinic in Clinic.objects.all():
        Team.objects.get_or_create(clinic=clinic, name="Recepção", defaults={"is_active": True})


def sem_recepcao(apps, schema_editor):
    Team = apps.get_model("inbox", "Team")
    Team.objects.filter(name="Recepção").delete()


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0005_atendimento_ciclo_de_vida'),
        ('tenants', '0004_clinic_appointments_backfilled_until'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='priority',
            field=models.CharField(blank=True, choices=[('', 'Normal'), ('high', 'Alta'), ('urgent', 'Urgente')], db_index=True, default='', help_text='Ordena a fila por urgência, não só por recência (RF-ATD-8).', max_length=6, verbose_name='Prioridade'),
        ),
        migrations.AlterField(
            model_name='message',
            name='activity_type',
            field=models.CharField(blank=True, choices=[('assigned', 'Assumiu o atendimento'), ('transferred', 'Transferiu'), ('resolved', 'Resolveu'), ('reopened', 'Reaberta'), ('snoozed', 'Adiou'), ('label_added', 'Marcou etiqueta'), ('label_removed', 'Removeu etiqueta'), ('priority_changed', 'Mudou a prioridade'), ('bot_started', 'IA assumiu'), ('bot_handoff', 'IA entregou para humano'), ('taken_over', 'Tomou o atendimento')], help_text='Preenchido só em evento de atividade (RF-ATD-4).', max_length=16, verbose_name='Tipo de evento'),
        ),
        migrations.CreateModel(
            name='ConversationLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deletado em')),
                ('name', models.CharField(max_length=40, verbose_name='Nome')),
                ('color', models.CharField(blank=True, help_text='Hex (#RRGGBB) do ponto que identifica a etiqueta na lista.', max_length=7, verbose_name='Cor')),
                ('is_active', models.BooleanField(default=True, help_text='Desligar APOSENTA a etiqueta: ela some da escolha e continua nas conversas que já a têm. Apagar reescreveria o passado - a conversa que foi uma reclamação continua tendo sido.', verbose_name='Ativa')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)ss', to='tenants.clinic', verbose_name='Clínica')),
            ],
            options={
                'verbose_name': 'Etiqueta de conversa',
                'verbose_name_plural': 'Etiquetas de conversa',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='conversation',
            name='labels',
            field=models.ManyToManyField(blank=True, help_text='Assunto (RF-ATD-9). LOCAL - nunca vai para o prontuário.', related_name='conversations', to='inbox.conversationlabel', verbose_name='Etiquetas'),
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deletado em')),
                ('name', models.CharField(max_length=60, verbose_name='Nome')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)ss', to='tenants.clinic', verbose_name='Clínica')),
            ],
            options={
                'verbose_name': 'Setor',
                'verbose_name_plural': 'Setores',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='conversation',
            name='team',
            field=models.ForeignKey(blank=True, help_text='Nasce no B1 sem tela: acrescentar FK a tabela que já cresceu custa migração e backfill. Transferência entre setores é o B2.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='inbox.team', verbose_name='Setor'),
        ),
        migrations.AddConstraint(
            model_name='conversationlabel',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('clinic', 'name'), name='uniq_conversation_label_name'),
        ),
        migrations.AddConstraint(
            model_name='team',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('clinic', 'name'), name='uniq_team_name'),
        ),
            migrations.RunPython(recepcao_por_clinica, sem_recepcao),
    ]
