# Generated by Django 5.2.12 on 2026-07-29 01:23

from django.db import migrations, models


def marcar_as_que_ja_baixaram(apps, schema_editor):
    """
    `state` nasce PENDING para todo mundo, e as mídias que já estão no disco
    apareceriam como "Baixando…" para sempre na tela. Quem tem arquivo está
    pronta; quem não tem continua pendente e a varredura de reprocesso resolve.
    """
    MediaAsset = apps.get_model("inbox", "MediaAsset")
    MediaAsset.objects.exclude(stored_file="").update(state="ready")


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0006_etiquetas_prioridade_setor'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaasset',
            name='duration_ms',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Duração (ms)'),
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='error',
            field=models.CharField(blank=True, max_length=200, verbose_name='Motivo da falha'),
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='filename',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nome do arquivo'),
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='state',
            field=models.CharField(choices=[('pending', 'Baixando'), ('ready', 'Pronta'), ('failed', 'Falhou')], default='pending', max_length=8, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='waveform',
            field=models.JSONField(blank=True, default=list, verbose_name='Onda'),
        ),
        migrations.RunPython(marcar_as_que_ja_baixaram, migrations.RunPython.noop),
    ]
