# Generated by Django 5.2.12 on 2026-07-29 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0007_mediaasset_duration_ms_mediaasset_error_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='reaction',
            field=models.CharField(blank=True, max_length=16, verbose_name='Reação'),
        ),
    ]
