# Generated by Django 5.2.12 on 2026-07-29 03:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0008_message_reaction'),
        ('tenants', '0004_clinic_appointments_backfilled_until'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='content_data',
            field=models.JSONField(blank=True, default=dict, verbose_name='Dados do conteúdo'),
        ),
        migrations.AlterField(
            model_name='message',
            name='kind',
            field=models.CharField(choices=[('text', 'Texto'), ('image', 'Imagem'), ('audio', 'Áudio'), ('video', 'Vídeo'), ('document', 'Documento'), ('sticker', 'Figurinha'), ('location', 'Localização'), ('contact', 'Contato'), ('interactive', 'Interativa'), ('template', 'Template'), ('unsupported', 'Não suportado'), ('activity', 'Evento')], default='text', max_length=12, verbose_name='Tipo'),
        ),
        migrations.CreateModel(
            name='MessageReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deletado em')),
                ('actor_kind', models.CharField(choices=[('contact', 'Paciente'), ('agent', 'Atendente')], max_length=7, verbose_name='Quem reagiu')),
                ('emoji', models.CharField(max_length=16, verbose_name='Emoji')),
                ('actor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='message_reactions', to=settings.AUTH_USER_MODEL, verbose_name='Atendente')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)ss', to='tenants.clinic', verbose_name='Clínica')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='inbox.conversation', verbose_name='Conversa')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='inbox.message', verbose_name='Mensagem')),
            ],
            options={
                'verbose_name': 'Reação',
                'verbose_name_plural': 'Reações',
                'indexes': [models.Index(fields=['conversation'], name='inbox_messa_convers_f56a86_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('actor_kind', 'contact')), fields=('message',), name='uma_reacao_do_contato_por_mensagem'), models.UniqueConstraint(condition=models.Q(('actor_kind', 'agent')), fields=('message', 'actor_user'), name='uma_reacao_por_atendente_por_mensagem')],
            },
        ),
    ]
