# Generated by Django 5.2.12 on 2026-07-29 03:57

from django.db import migrations


def campo_vira_linha(apps, schema_editor):
    """
    O `Message.reaction` de ontem vira uma linha na tabela nova.

    Tudo o que existe hoje veio do webhook, ou seja, do CONTATO — o atendente
    ainda não tem como reagir. Nenhuma reação se perde na troca de desenho.
    """
    Message = apps.get_model("inbox", "Message")
    MessageReaction = apps.get_model("inbox", "MessageReaction")

    MessageReaction.objects.bulk_create(
        [
            MessageReaction(
                clinic_id=mensagem.clinic_id,
                message_id=mensagem.pk,
                conversation_id=mensagem.conversation_id,
                actor_kind="contact",
                emoji=mensagem.reaction,
            )
            for mensagem in Message.objects.exclude(reaction="").only(
                "pk", "clinic_id", "conversation_id", "reaction"
            )
        ]
    )


def linha_vira_campo(apps, schema_editor):
    """Volta atrás: só as do contato cabem no campo único."""
    Message = apps.get_model("inbox", "Message")
    MessageReaction = apps.get_model("inbox", "MessageReaction")

    for reacao in MessageReaction.objects.filter(actor_kind="contact"):
        Message.objects.filter(pk=reacao.message_id).update(reaction=reacao.emoji)


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0009_message_content_data_alter_message_kind_and_more'),
    ]

    operations = [
        migrations.RunPython(campo_vira_linha, linha_vira_campo),
        migrations.RemoveField(
            model_name='message',
            name='reaction',
        ),
    ]
