# Generated by Django 5.2.12 on 2026-07-29 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0010_remove_message_reaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='auth_error_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Falhas de credencial'),
        ),
        migrations.AddField(
            model_name='channel',
            name='disconnect_reason',
            field=models.CharField(blank=True, max_length=200, verbose_name='Motivo'),
        ),
        migrations.AddField(
            model_name='channel',
            name='disconnected_at',
            field=models.DateTimeField(blank=True, help_text='Null = canal vivo. Preenchido, a clínica inteira parou de responder.', null=True, verbose_name='Desconectado desde'),
        ),
    ]
