# Generated by Django 5.2.12 on 2026-07-29 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0011_channel_auth_error_count_channel_disconnect_reason_and_more'),
        ('tenants', '0004_clinic_appointments_backfilled_until'),
    ]

    operations = [
        migrations.AddField(
            model_name='quickreply',
            name='shortcut',
            field=models.CharField(blank=True, help_text='Sem a barra. Minúsculo, sem espaço, único na clínica.', max_length=32, verbose_name='Atalho'),
        ),
        migrations.AddConstraint(
            model_name='quickreply',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), models.Q(('shortcut', ''), _negated=True)), fields=('clinic', 'shortcut'), name='uniq_quick_reply_shortcut'),
        ),
    ]
