# Generated by Django 5.2.12 on 2026-08-11 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0013_message_edited_at'),
        ('tenants', '0006_remove_clinicbusinesshours_uniq_business_hours_weekday_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReactivationMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deletado em')),
                ('variables', models.JSONField(blank=True, default=dict, verbose_name='Variáveis')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)ss', to='tenants.clinic', verbose_name='Clínica')),
                ('template', models.ForeignKey(blank=True, help_text='Nulo enquanto a conta da Meta não tiver template de resgate.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reactivation_messages', to='inbox.whatsapptemplate', verbose_name='Template')),
            ],
            options={
                'verbose_name': 'Mensagem de reativação',
                'verbose_name_plural': 'Mensagens de reativação',
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('clinic',), name='uniq_reactivation_message_per_clinic')],
            },
        ),
    ]
