# Generated by Django 5.2.12 on 2026-08-13 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0014_reactivationmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsapptemplate',
            name='meta_template_id',
            field=models.CharField(blank=True, db_index=True, max_length=64, verbose_name='Id na Meta'),
        ),
        migrations.AddField(
            model_name='whatsapptemplate',
            name='rejection_reason',
            field=models.TextField(blank=True, verbose_name='Motivo da recusa'),
        ),
    ]
