# Generated by Django 5.2.12 on 2026-08-13 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0015_whatsapptemplate_meta_template_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsapptemplate',
            name='quality_score',
            field=models.CharField(blank=True, max_length=10, verbose_name='Qualidade'),
        ),
    ]
