# Generated by Django 5.2.12 on 2026-08-18 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0016_whatsapptemplate_quality_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='is_test',
            field=models.BooleanField(default=False, verbose_name='Canal de teste'),
        ),
    ]
