# Generated by Django 5.2.12 on 2026-08-18 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0017_channel_is_test'),
        ('tenants', '0006_remove_clinicbusinesshours_uniq_business_hours_weekday_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='channel',
            name='one_channel_per_clinic',
        ),
        migrations.AddConstraint(
            model_name='channel',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('is_test', False)), fields=('clinic',), name='one_channel_per_clinic'),
        ),
    ]
