# Generated by Django 5.2.12 on 2026-08-18 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0018_remove_channel_one_channel_per_clinic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsapptemplate',
            name='parameter_format',
            field=models.CharField(blank=True, max_length=20, verbose_name='Formato dos parâmetros'),
        ),
    ]
