# Generated by Django 5.2.12 on 2026-08-19 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0019_whatsapptemplate_parameter_format'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='send_attempted_at',
            field=models.DateTimeField(blank=True, help_text='Carimbado ANTES de falar com a Meta. Serve para distinguir "nunca foi despachada" de "foi despachada e não sabemos o que houve" - sem ele, as duas ficam idênticas no banco (sem status e sem identificador) e é impossível dizer se reenviar duplica.', null=True, verbose_name='Envio tentado em'),
        ),
    ]
