# Generated by Django 5.2.12 on 2026-08-19 16:07

from django.db import migrations, models


def adotar_rascunhos_locais(apps, schema_editor):
    """
    Quem é rascunho LOCAL passa a ser da conta atual da clínica (RF-INB-3.3).

    Rascunho sem `meta_template_id` nunca existiu na Meta: ele seria submetido
    à conta que a clínica usa HOJE, então é dela que ele é.

    ⚠️ O que TEM id da Meta fica sem conta de propósito, e por isso some da
    tela: não dá para adivinhar de qual conta veio, e chutar a atual seria
    exatamente a mistura que este trabalho veio desfazer. A primeira
    sincronização recarimba o que existe de verdade; o que não voltar era da
    conta antiga.
    """
    Channel = apps.get_model("inbox", "Channel")
    WhatsAppTemplate = apps.get_model("inbox", "WhatsAppTemplate")

    contas = {
        c.clinic_id: c.waba_id
        for c in Channel.objects.filter(is_test=False).exclude(waba_id="")
    }
    for clinic_id, waba_id in contas.items():
        WhatsAppTemplate.objects.filter(
            clinic_id=clinic_id, meta_template_id=""
        ).update(waba_id=waba_id)


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0020_message_send_attempted_at'),
        ('tenants', '0006_remove_clinicbusinesshours_uniq_business_hours_weekday_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='whatsapptemplate',
            name='uniq_template',
        ),
        migrations.AddField(
            model_name='whatsapptemplate',
            name='waba_id',
            field=models.CharField(blank=True, db_index=True, max_length=32, verbose_name='Conta da Meta'),
        ),
        migrations.RunPython(adotar_rascunhos_locais, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='whatsapptemplate',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('clinic', 'waba_id', 'name', 'language'), name='uniq_template'),
        ),
    ]
