# Generated by Django 5.2.12 on 2026-08-19 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0022_channel_conexao_incorporada'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='from_phone',
            field=models.BooleanField(default=False, verbose_name='Enviada pelo celular'),
        ),
    ]
