# Generated by Django 5.2.12 on 2026-08-21 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0023_message_from_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='revoked_at',
            field=models.DateTimeField(blank=True, help_text='O paciente apagou esta mensagem no WhatsApp dele (webhook `revoke`, só em coexistência). ⚠️ O CONTEÚDO FICA: o registro do atendimento é da clínica, e a tela apenas o esmaece e avisa. Apagar aqui junto reescreveria o que a recepção leu e respondeu.', null=True, verbose_name='Apagada pelo contato em'),
        ),
    ]
