# Generated by Django 5.2.12 on 2026-08-21 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0024_message_revoked_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='activity_type',
            field=models.CharField(blank=True, choices=[('assigned', 'Assumiu o atendimento'), ('transferred', 'Transferiu'), ('resolved', 'Resolveu'), ('reopened', 'Reaberta'), ('snoozed', 'Adiou'), ('label_added', 'Marcou etiqueta'), ('label_removed', 'Removeu etiqueta'), ('priority_changed', 'Mudou a prioridade'), ('bot_started', 'IA assumiu'), ('bot_handoff', 'IA entregou para humano'), ('taken_over', 'Tomou o atendimento'), ('number_changed', 'Trocou de número')], help_text='Preenchido só em evento de atividade (RF-ATD-4).', max_length=16, verbose_name='Tipo de evento'),
        ),
    ]
