# Generated by Django 5.2.12 on 2026-08-21 16:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0025_alter_message_activity_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='revoked_by',
            field=models.ForeignKey(blank=True, help_text='Quem apagou PELO CRM. Vazio quando veio do WhatsApp: aí quem apagou foi o paciente (mensagem recebida) ou alguém no app do celular da clínica (mensagem enviada, `from_phone`).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Apagada por'),
        ),
        migrations.AlterField(
            model_name='message',
            name='revoked_at',
            field=models.DateTimeField(blank=True, help_text='Quando esta mensagem foi apagada, por qualquer um dos TRÊS caminhos: o paciente no WhatsApp dele, a clínica no app do celular (os dois pelo webhook `revoke`, só em coexistência) ou alguém aqui no CRM. ⚠️ O CONTEÚDO FICA nos três: o registro do atendimento é da clínica, e a tela apenas o esmaece e avisa. Apagar junto reescreveria o que a recepção leu e respondeu.', null=True, verbose_name='Apagada pelo contato em'),
        ),
    ]
