# Generated by Django 5.2.12 on 2026-07-09 15:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Criação'), ('UPDATE', 'Atualização'), ('DELETE', 'Exclusão'), ('RESTORE', 'Restauração'), ('READ', 'Leitura'), ('LOGIN', 'Login'), ('LOGIN_FAILED', 'Login falhou'), ('LOGOUT', 'Logout')], max_length=50, verbose_name='Ação')),
                ('resource', models.CharField(max_length=100, verbose_name='Recurso')),
                ('resource_id', models.CharField(max_length=50, verbose_name='ID do recurso')),
                ('payload', models.JSONField(default=dict, verbose_name='Payload')),
                ('ip_address', models.GenericIPAddressField(null=True, verbose_name='Endereço IP')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
                ('clinic', models.ForeignKey(blank=True, help_text='Nula em eventos globais (login, ações do plano plataforma).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='tenants.clinic', verbose_name='Clínica')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Log de auditoria',
                'verbose_name_plural': 'Logs de auditoria',
                'indexes': [models.Index(fields=['user', 'timestamp'], name='core_auditl_user_id_7b678c_idx'), models.Index(fields=['resource', 'resource_id'], name='core_auditl_resourc_55ca2e_idx'), models.Index(fields=['clinic', 'timestamp'], name='core_auditl_clinic__8bf86f_idx')],
            },
        ),
    ]
