# Generated by Django 5.2.12 on 2026-07-27 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('CREATE', 'Criação'), ('UPDATE', 'Atualização'), ('DELETE', 'Exclusão'), ('RESTORE', 'Restauração'), ('READ', 'Leitura'), ('READ_CPF', 'Leitura de CPF'), ('LOGIN', 'Login'), ('LOGIN_FAILED', 'Login falhou'), ('LOGOUT', 'Logout')], max_length=50, verbose_name='Ação'),
        ),
    ]
