# Generated by Django 5.2.12 on 2026-07-09 15:54

import apps.core.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deletado em')),
                ('name', models.CharField(max_length=160, verbose_name='Nome')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('timezone', models.CharField(default='America/Fortaleza', help_text='Base do send_time das jornadas e dos horários exibidos.', max_length=48, verbose_name='Fuso horário')),
                ('ehr_provider', models.CharField(blank=True, choices=[('vsaude', 'vSaúde')], help_text='Vazio = clínica sem integração de prontuário.', max_length=20, verbose_name='Provedor de EHR')),
                ('ehr_credentials', apps.core.fields.EncryptedJSONField(default=dict, help_text='Ex.: {"api_key": "..."} — cifrado em repouso.', verbose_name='Credenciais do EHR')),
                ('ehr_external_tenant_id', models.CharField(blank=True, max_length=64, verbose_name='ID externo no EHR')),
            ],
            options={
                'verbose_name': 'Clínica',
                'verbose_name_plural': 'Clínicas',
            },
        ),
    ]
