# Generated by Django 5.2.12 on 2026-07-09 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='active_window_days',
            field=models.PositiveSmallIntegerField(default=90, help_text='Paciente é ATIVO se consultou nos últimos N dias (RF-PAC-2). Padrão da clínica; cada profissional pode sobrescrever o seu.', verbose_name='Janela de paciente ativo (dias)'),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='ehr_provider',
            field=models.CharField(blank=True, choices=[('vsaude', 'vSaúde'), ('fake', 'Fake (desenvolvimento)')], help_text='Vazio = clínica sem integração de prontuário.', max_length=20, verbose_name='Provedor de EHR'),
        ),
    ]
