# Generated by Django 5.2.12 on 2026-07-20 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_clinic_active_window_days_alter_clinic_ehr_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='ehr_push_enabled',
            field=models.BooleanField(default=False, help_text='Trava de segurança do write-through: desligada, mutações locais NÃO são empurradas ao EHR (fase de validação só-leitura). O pull continua normal. Ligar só depois de validar a leitura.', verbose_name='Escrita no EHR habilitada'),
        ),
    ]
