# Generated by Django 5.2.12 on 2026-07-21 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_clinic_ehr_push_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='appointments_backfilled_until',
            field=models.DateField(blank=True, help_text="Marca-d'água do backfill resumível da agenda: cada sincronização recua um pedaço e grava aqui, até o limite de histórico. Vazio = backfill ainda não começou.", null=True, verbose_name='Agenda importada até (para trás)'),
        ),
    ]
