# Generated by Django 5.2.12 on 2026-07-31 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0004_clinic_appointments_backfilled_until'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicBusinessHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deletado em')),
                ('weekday', models.PositiveSmallIntegerField(choices=[(0, 'Segunda-feira'), (1, 'Terça-feira'), (2, 'Quarta-feira'), (3, 'Quinta-feira'), (4, 'Sexta-feira'), (5, 'Sábado'), (6, 'Domingo')], verbose_name='Dia da semana')),
                ('opens_at', models.TimeField(verbose_name='Abre às')),
                ('closes_at', models.TimeField(verbose_name='Fecha às')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_hours', to='tenants.clinic', verbose_name='Clínica')),
            ],
            options={
                'verbose_name': 'Horário de funcionamento',
                'verbose_name_plural': 'Horários de funcionamento',
                'ordering': ['weekday', 'opens_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('clinic', 'weekday'), name='uniq_business_hours_weekday')],
            },
        ),
    ]
