# Generated by Django 5.2.12 on 2026-08-05 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0005_clinicbusinesshours'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='clinicbusinesshours',
            name='uniq_business_hours_weekday',
        ),
        migrations.AddConstraint(
            model_name='clinicbusinesshours',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('clinic', 'weekday', 'opens_at'), name='uniq_business_hours_faixa'),
        ),
    ]
