# Generated by Django 5.2.12 on 2026-08-21 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0006_remove_clinicbusinesshours_uniq_business_hours_weekday_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='status',
            field=models.CharField(choices=[('active', 'Ativa'), ('suspended', 'Suspensa')], default='active', help_text='Suspensa: a equipe não entra, o robô não responde e as sequências não disparam. As mensagens que o paciente mandar CONTINUAM sendo recebidas (RF-ADM-1.7).', max_length=12, verbose_name='Situação'),
        ),
        migrations.AddField(
            model_name='clinic',
            name='suspended_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Suspensa em'),
        ),
        migrations.AddField(
            model_name='clinic',
            name='suspension_category',
            field=models.CharField(blank=True, choices=[('non_payment', 'Falta de pagamento'), ('abuse', 'Uso indevido'), ('clinic_request', 'A pedido da clínica'), ('other', 'Outro')], max_length=20, verbose_name='Motivo da suspensão'),
        ),
        migrations.AddField(
            model_name='clinic',
            name='suspension_reason',
            field=models.TextField(blank=True, help_text="Obrigatório ao suspender: é o que responde 'por quê' meses depois.", max_length=256, verbose_name='Detalhe da suspensão'),
        ),
    ]
