# Generated by Django 5.2.12 on 2026-07-31 15:21

import apps.automation.models.flow
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inbox', '0013_message_edited_at'),
        ('patients', '0011_remove_patient_clinical_synced_at'),
        ('tenants', '0005_clinicbusinesshours'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deletado em')),
                ('name', models.CharField(max_length=120, verbose_name='Nome')),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('active', 'Ativo'), ('archived', 'Arquivado')], default='draft', max_length=20, verbose_name='Situação')),
                ('trigger', models.CharField(choices=[('first_inbound', 'Primeira mensagem do contato'), ('keyword', 'Palavra-chave'), ('manual', 'Disparo manual do atendente')], default='first_inbound', max_length=20, verbose_name='Gatilho')),
                ('trigger_config', models.JSONField(blank=True, default=dict, help_text='Para palavra-chave: {"keywords": ["orçamento"], "match": "contains"}.', verbose_name='Configuração do gatilho')),
                ('only_outside_hours', models.BooleanField(default=False, help_text='Ligado, o fluxo só dispara com a clínica fechada - dentro do expediente a conversa vai direto para a recepção. É o modo que faz sentido para uma recepção pequena (RF-FLW-5.1).', verbose_name='Só fora do horário de funcionamento')),
                ('priority', models.PositiveSmallIntegerField(default=10, help_text='Desempate quando mais de um fluxo casa com a mesma mensagem: MENOR vence. Empatou, vence o ativado por último (RF-FLW-5.2).', verbose_name='Prioridade')),
                ('fallback', models.JSONField(default=apps.automation.models.flow.default_fallback, verbose_name='Política de fallback')),
                ('activated_at', models.DateTimeField(blank=True, null=True, verbose_name='Ativado em')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)ss', to='tenants.clinic', verbose_name='Clínica')),
            ],
            options={
                'verbose_name': 'Fluxo de atendimento',
                'verbose_name_plural': 'Fluxos de atendimento',
                'ordering': ['priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FlowRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deletado em')),
                ('status', models.CharField(choices=[('active', 'Em andamento'), ('completed', 'Concluída'), ('handed_off', 'Entregue a um humano'), ('timed_out', 'Encerrada por inatividade'), ('paused_by_agent', 'Pausada porque um atendente assumiu'), ('failed', 'Falhou')], default='active', max_length=20, verbose_name='Situação')),
                ('current_node', models.CharField(blank=True, max_length=100, verbose_name='Nó atual')),
                ('reprompt_count', models.PositiveSmallIntegerField(default=0, verbose_name='Repetições')),
                ('vars', models.JSONField(blank=True, default=dict, help_text='O que os nós de coleta capturaram. Escopo da execução: morre com ela.', verbose_name='Variáveis')),
                ('last_advanced_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='Base da varredura de inatividade (RF-FLW-11).', verbose_name='Último avanço')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='Encerrada em')),
                ('end_reason', models.CharField(blank=True, max_length=40, verbose_name='Motivo do fim')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)ss', to='tenants.clinic', verbose_name='Clínica')),
                ('contact', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flow_runs', to='patients.contact', verbose_name='Contato')),
                ('conversation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flow_runs', to='inbox.conversation', verbose_name='Conversa')),
                ('flow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='automation.flow', verbose_name='Fluxo')),
            ],
            options={
                'verbose_name': 'Execução de fluxo',
                'verbose_name_plural': 'Execuções de fluxo',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FlowRunEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deletado em')),
                ('node_key', models.CharField(blank=True, max_length=100, verbose_name='Nó')),
                ('event_type', models.CharField(max_length=20, verbose_name='Tipo')),
                ('data', models.JSONField(blank=True, default=dict, verbose_name='Dados')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='automation.flowrun', verbose_name='Execução')),
            ],
            options={
                'verbose_name': 'Evento de execução',
                'verbose_name_plural': 'Eventos de execução',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='FlowVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deletado em')),
                ('number', models.PositiveIntegerField(verbose_name='Número')),
                ('graph', models.JSONField(default=apps.automation.models.flow.empty_graph, help_text='{"nodes": [...], "edges": [...], "entry_node": "n1"}', verbose_name='Grafo')),
                ('published_at', models.DateTimeField(blank=True, help_text='Nula = rascunho. Publicar é o que a torna elegível a virar a versão corrente.', null=True, verbose_name='Publicada em')),
                ('flow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='automation.flow', verbose_name='Fluxo')),
            ],
            options={
                'verbose_name': 'Versão do fluxo',
                'verbose_name_plural': 'Versões do fluxo',
                'ordering': ['-number'],
            },
        ),
        migrations.AddField(
            model_name='flowrun',
            name='version',
            field=models.ForeignKey(help_text='A versão em que ESTA execução começou e na qual ela termina (RF-FLW-1.1).', on_delete=django.db.models.deletion.RESTRICT, related_name='runs', to='automation.flowversion', verbose_name='Versão'),
        ),
        migrations.AddField(
            model_name='flow',
            name='current_version',
            field=models.ForeignKey(blank=True, help_text='A versão que as execuções NOVAS usam. Nula enquanto nunca foi ativado.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='automation.flowversion', verbose_name='Versão publicada'),
        ),
        migrations.AddConstraint(
            model_name='flowversion',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('flow', 'number'), name='uniq_flow_version_number'),
        ),
        migrations.AddConstraint(
            model_name='flowrun',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('status', 'active')), fields=('clinic', 'contact'), name='uniq_run_ativo_por_contato'),
        ),
        migrations.AddConstraint(
            model_name='flow',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('clinic', 'name'), name='uniq_flow_name'),
        ),
    ]
