# Generated by Django 5.2.12 on 2026-07-31 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flowrun',
            name='wake_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text="Preenchido pelo nó 'Aguardar': quando a varredura deve retomar sozinha. Nulo = a execução espera o paciente falar, não o relógio.", null=True, verbose_name='Acordar em'),
        ),
    ]
