# Generated by Django 5.2.12 on 2026-08-13 20:41

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0003_despedida_e_timeout_de_20h'),
        ('patients', '0012_contact_marketing_opt_out'),
        ('scheduling', '0009_fake_status_map_parity'),
        ('tenants', '0006_remove_clinicbusinesshours_uniq_business_hours_weekday_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deletado em')),
                ('name', models.CharField(max_length=120, verbose_name='Nome')),
                ('is_active', models.BooleanField(default=False, help_text='Nasce DESLIGADA (RF-SEQ-12): ligar é gesto do gestor. Desligada, os disparos ficam segurados e o calendário retoma ao religar.', verbose_name='Ativa')),
                ('is_marketing', models.BooleanField(default=True, help_text='Ligado, respeita o opt-out do contato (RF-SEQ-8.2). Desligue em sequência operacional - quem pediu para parar promoção não pediu para parar de confirmar consulta.', verbose_name='É de marketing')),
                ('enroll_on_appointment', models.BooleanField(default=False, help_text='Porta automática (RF-SEQ-3.4): consulta futura criada aqui ou espelhada do prontuário inscreve, ancorada na data dela.', verbose_name='Inscrever quando marcar consulta')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)ss', to='tenants.clinic', verbose_name='Clínica')),
            ],
            options={
                'verbose_name': 'Sequência',
                'verbose_name_plural': 'Sequências',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SequenceStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deletado em')),
                ('order', models.PositiveSmallIntegerField(verbose_name='Ordem')),
                ('name', models.CharField(blank=True, max_length=120, verbose_name='Nome')),
                ('offset_days', models.SmallIntegerField(help_text='Negativo é antes: -1 é a véspera da consulta. Zero é o próprio dia.', verbose_name='Dias da âncora')),
                ('send_time', models.TimeField(default=datetime.time(8, 0), help_text='Hora LOCAL da clínica, não do servidor.', verbose_name='Horário')),
                ('expire_hours', models.PositiveSmallIntegerField(default=24, help_text='Quanto tempo insistir quando o disparo encontra a conversa ocupada. Vencido, o passo é PULADO com o motivo gravado, e o calendário segue - o passo seguinte não desliza (RF-SEQ-5.1).', verbose_name='Validade (horas)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('flow', models.ForeignKey(help_text='O fluxo que este passo dispara. Precisa estar publicado na hora do disparo.', on_delete=django.db.models.deletion.RESTRICT, related_name='sequence_steps', to='automation.flow', verbose_name='Fluxo')),
                ('sequence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='automation.sequence', verbose_name='Sequência')),
            ],
            options={
                'verbose_name': 'Passo da sequência',
                'verbose_name_plural': 'Passos da sequência',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SequenceEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deletado em')),
                ('anchor_at', models.DateTimeField(help_text='O instante zero dos deslocamentos dos passos.', verbose_name='Âncora')),
                ('source', models.CharField(choices=[('flow_node', 'Nó de fluxo'), ('patient_record', 'Ficha do paciente'), ('batch', 'Lote'), ('appointment', 'Consulta criada')], max_length=20, verbose_name='Porta de entrada')),
                ('status', models.CharField(choices=[('active', 'Ativa'), ('completed', 'Concluída'), ('canceled', 'Cancelada')], default='active', max_length=20, verbose_name='Situação')),
                ('end_reason', models.CharField(blank=True, max_length=30, verbose_name='Motivo do fim')),
                ('next_dispatch_at', models.DateTimeField(blank=True, db_index=True, help_text='Base da varredura. Nulo quando não há mais passo pela frente.', null=True, verbose_name='Próximo disparo')),
                ('appointment', models.ForeignKey(blank=True, help_text='Só na porta automática (RF-SEQ-3.4). É ela que ancora os deslocamentos.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sequence_enrollments', to='scheduling.appointment', verbose_name='Consulta')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)ss', to='tenants.clinic', verbose_name='Clínica')),
                ('contact', models.ForeignKey(help_text='Quem RECEBE. A inscrição é do número, não do paciente (RF-SEQ-3.6).', on_delete=django.db.models.deletion.CASCADE, related_name='sequence_enrollments', to='patients.contact', verbose_name='Contato')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sequence_enrollments', to='patients.patient', verbose_name='Paciente')),
                ('sequence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='automation.sequence', verbose_name='Sequência')),
                ('current_step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='automation.sequencestep', verbose_name='Passo atual')),
            ],
            options={
                'verbose_name': 'Inscrição em sequência',
                'verbose_name_plural': 'Inscrições em sequência',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SequenceDispatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deletado em')),
                ('scheduled_for', models.DateTimeField(verbose_name='Previsto para')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Resolvido em')),
                ('status', models.CharField(choices=[('started', 'Fluxo disparado'), ('skipped', 'Pulado')], max_length=20, verbose_name='Situação')),
                ('skip_reason', models.CharField(blank=True, max_length=30, verbose_name='Motivo do pulo')),
                ('flow_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='automation.flowrun', verbose_name='Execução gerada')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispatches', to='automation.sequenceenrollment', verbose_name='Inscrição')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='dispatches', to='automation.sequencestep', verbose_name='Passo')),
            ],
            options={
                'verbose_name': 'Disparo da sequência',
                'verbose_name_plural': 'Disparos da sequência',
                'ordering': ['scheduled_for'],
            },
        ),
        migrations.AddConstraint(
            model_name='sequence',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('clinic', 'name'), name='uniq_sequence_name'),
        ),
        migrations.AddConstraint(
            model_name='sequencestep',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('sequence', 'order'), name='uniq_step_order'),
        ),
        migrations.AddConstraint(
            model_name='sequenceenrollment',
            constraint=models.UniqueConstraint(condition=models.Q(('appointment__isnull', True), ('deleted_at__isnull', True), ('status', 'active')), fields=('sequence', 'contact'), name='uniq_enrollment_ativo_por_contato'),
        ),
        migrations.AddConstraint(
            model_name='sequenceenrollment',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('status', 'active')), fields=('sequence', 'appointment'), name='uniq_enrollment_ativo_por_consulta'),
        ),
        migrations.AddConstraint(
            model_name='sequencedispatch',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('enrollment', 'step'), name='uniq_dispatch_por_passo'),
        ),
    ]
