# Generated by Django 5.2.12 on 2026-08-14 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0004_sequence_sequencestep_sequenceenrollment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sequenceenrollment',
            name='held_since',
            field=models.DateTimeField(blank=True, help_text='Quando o disparo começou a ser adiado (RF-SEQ-11). Nulo quando não há nada segurando.', null=True, verbose_name='Segurando desde'),
        ),
        migrations.AddField(
            model_name='sequenceenrollment',
            name='hold_reason',
            field=models.CharField(blank=True, help_text='Por que o disparo não sai AGORA. Sem isto o painel mostraria a hora passada e nenhuma explicação, que é o mesmo mistério que os motivos de pulo existem para acabar.', max_length=40, verbose_name='Motivo de estar segurando'),
        ),
    ]
