# Generated by Django 5.2.12 on 2026-08-14 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0005_sequenceenrollment_held_since_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sequence',
            name='conversion_days',
            field=models.PositiveSmallIntegerField(default=7, help_text='Quantos dias depois de um disparo uma consulta nova conta como resultado dele (RF-SEQ-11.2). É por sequência porque confirmar véspera e resgatar inativo têm ritmos diferentes.', verbose_name='Janela do agendou (dias)'),
        ),
    ]
