# Generated by Django 5.2.12 on 2026-08-18 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0006_sequence_conversion_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='flowrun',
            name='is_test',
            field=models.BooleanField(default=False, verbose_name='Execução de teste'),
        ),
    ]
