# Generated by Django 5.2.12 on 2026-08-18 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0007_flowrun_is_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='sequence',
            name='exit_on_appointment',
            field=models.BooleanField(default=False, help_text='Saída configurável (RF-SEQ-6.2): consulta futura marcada tira das trilhas de divulgação. Não vale onde `enroll_on_appointment` está ligado - ali a consulta é a porta de ENTRADA, e quem decide pular um passo pós-consulta é o RF-SEQ-7.', verbose_name='Quem marcar consulta sai'),
        ),
        migrations.AddField(
            model_name='sequence',
            name='exit_on_reply',
            field=models.BooleanField(default=False, help_text='Saída configurável (RF-SEQ-6.2): quem responder DEPOIS de receber um disparo desta trilha para de receber os próximos passos. Nasce ligada em divulgação e desligada em atendimento.', verbose_name='Quem responder sai'),
        ),
    ]
