# Generated by Django 5.2.12 on 2026-08-20 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    """
    O cadastro de destinos permitidos do nó HTTP (RF-FLW-16.1 item a).

    Nasce vazio de propósito: nenhum destino é presumido, e um nó sem destino
    escolhido não publica.
    """


    dependencies = [
        ('automation', '0009_gatilho_de_novo_atendimento'),
        ('tenants', '0006_remove_clinicbusinesshours_uniq_business_hours_weekday_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HttpDestination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deletado em')),
                ('name', models.CharField(help_text="Como este destino aparece na lista do nó. Ex.: 'ERP da recepção'.", max_length=80, verbose_name='Nome')),
                ('url', models.TextField(help_text='Precisa ser https, sem usuário e senha embutidos, e apontar para fora da rede interna.', verbose_name='Endereço')),
                ('secret', models.CharField(blank=True, default='', help_text='Enviado no cabeçalho `X-MedEssence-Secret` para o destino confirmar que a chamada é nossa. Em branco, nada é enviado.', max_length=200, verbose_name='Segredo')),
                ('is_active', models.BooleanField(default=True, help_text='Desligado, os nós que apontam para ele param de chamar e seguem pela saída de falha.', verbose_name='Ativo')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)ss', to='tenants.clinic', verbose_name='Clínica')),
            ],
            options={
                'verbose_name': 'Destino de requisição',
                'verbose_name_plural': 'Destinos de requisição',
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('clinic', 'name'), name='uniq_http_destination_name')],
            },
        ),
    ]
