# Generated by Django 5.2.12 on 2026-07-09 17:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CareUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deletado em')),
                ('name', models.CharField(max_length=160, verbose_name='Nome')),
                ('external_id', models.CharField(max_length=32, verbose_name='ID no EHR')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)ss', to='tenants.clinic', verbose_name='Clínica')),
            ],
            options={
                'verbose_name': 'Unidade',
                'verbose_name_plural': 'Unidades',
            },
        ),
        migrations.CreateModel(
            name='EHRStatusMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deletado em')),
                ('provider', models.CharField(choices=[('vsaude', 'vSaúde')], max_length=20, verbose_name='Provedor')),
                ('source_status', models.CharField(max_length=8, verbose_name='Código do EHR')),
                ('status', models.CharField(choices=[('scheduled', 'Agendada'), ('confirmed', 'Confirmada'), ('in_progress', 'Em atendimento'), ('completed', 'Realizada'), ('no_show', 'Faltou'), ('canceled', 'Cancelada')], max_length=15, verbose_name='Status normalizado')),
            ],
            options={
                'verbose_name': 'Mapa de status do EHR',
                'verbose_name_plural': 'Mapas de status do EHR',
                'constraints': [models.UniqueConstraint(fields=('provider', 'source_status'), name='uniq_status_map')],
            },
        ),
        migrations.CreateModel(
            name='InsuranceCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deletado em')),
                ('name', models.CharField(max_length=160, verbose_name='Nome')),
                ('external_id', models.CharField(max_length=32, verbose_name='ID no EHR')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)ss', to='tenants.clinic', verbose_name='Clínica')),
            ],
            options={
                'verbose_name': 'Convênio',
                'verbose_name_plural': 'Convênios',
            },
        ),
        migrations.CreateModel(
            name='InsurancePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deletado em')),
                ('name', models.CharField(max_length=160, verbose_name='Nome')),
                ('external_id', models.CharField(max_length=32, verbose_name='ID no EHR')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)ss', to='tenants.clinic', verbose_name='Clínica')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='scheduling.insurancecompany', verbose_name='Convênio')),
            ],
            options={
                'verbose_name': 'Plano de convênio',
                'verbose_name_plural': 'Planos de convênio',
            },
        ),
        migrations.CreateModel(
            name='Practitioner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deletado em')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('license_number', models.CharField(blank=True, max_length=40, verbose_name='Registro (CRM)')),
                ('external_id', models.CharField(blank=True, max_length=64, verbose_name='ID no EHR')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)ss', to='tenants.clinic', verbose_name='Clínica')),
                ('user', models.ForeignKey(blank=True, help_text='Liga o profissional ao login - carteira do médico.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='practitioners', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Profissional',
                'verbose_name_plural': 'Profissionais',
            },
        ),
        migrations.CreateModel(
            name='Procedure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deletado em')),
                ('name', models.CharField(max_length=160, verbose_name='Nome')),
                ('external_id', models.CharField(max_length=32, verbose_name='ID no EHR')),
                ('duration_min', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Duração (min)')),
                ('remotely', models.BooleanField(default=False, verbose_name='Remoto')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)ss', to='tenants.clinic', verbose_name='Clínica')),
            ],
            options={
                'verbose_name': 'Procedimento',
                'verbose_name_plural': 'Procedimentos',
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deletado em')),
                ('starts_at', models.DateTimeField(db_index=True, verbose_name='Início')),
                ('duration_min', models.PositiveSmallIntegerField(default=30, verbose_name='Duração (min)')),
                ('status', models.CharField(choices=[('scheduled', 'Agendada'), ('confirmed', 'Confirmada'), ('in_progress', 'Em atendimento'), ('completed', 'Realizada'), ('no_show', 'Faltou'), ('canceled', 'Cancelada')], default='scheduled', max_length=15, verbose_name='Status')),
                ('source_status', models.CharField(blank=True, help_text='Código numérico observado (10, 81, 90, 100…) - P4.', max_length=8, verbose_name='Status cru do EHR')),
                ('remotely', models.BooleanField(default=False, verbose_name='Remoto')),
                ('external_id', models.CharField(blank=True, max_length=64, verbose_name='ID no EHR')),
                ('raw_payload', models.JSONField(blank=True, default=dict, verbose_name='Payload cru')),
                ('sync_status', models.CharField(choices=[('synced', 'Sincronizado'), ('pending', 'Aguardando sincronização'), ('failed', 'Falha na sincronização')], default='synced', max_length=10, verbose_name='Sincronização')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)ss', to='tenants.clinic', verbose_name='Clínica')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='appointments', to='patients.patient', verbose_name='Paciente')),
                ('care_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='scheduling.careunit', verbose_name='Unidade')),
                ('insurance_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='scheduling.insurancecompany', verbose_name='Convênio')),
                ('insurance_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='scheduling.insuranceplan', verbose_name='Plano')),
                ('practitioner', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='appointments', to='scheduling.practitioner', verbose_name='Profissional')),
                ('procedure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='scheduling.procedure', verbose_name='Procedimento')),
            ],
            options={
                'verbose_name': 'Consulta',
                'verbose_name_plural': 'Consultas',
                'constraints': [models.UniqueConstraint(condition=models.Q(('external_id', ''), _negated=True), fields=('clinic', 'external_id'), name='uniq_appt_ext')],
            },
        ),
    ]
