# Generated by Django 5.2.12 on 2026-07-09 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ehrstatusmap',
            name='provider',
            field=models.CharField(choices=[('vsaude', 'vSaúde'), ('fake', 'Fake (desenvolvimento)')], max_length=20, verbose_name='Provedor'),
        ),
        migrations.AlterField(
            model_name='practitioner',
            name='license_number',
            field=models.CharField(blank=True, help_text='licenceNumber do EHR - pode incluir RQE e texto livre.', max_length=120, verbose_name='Registro (CRM)'),
        ),
    ]
