# Generated by Django 5.2.12 on 2026-07-09 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0003_seed_vsaude_status_map'),
    ]

    operations = [
        migrations.AddField(
            model_name='practitioner',
            name='active_window_days',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Sobrescreve o padrão da clínica para a carteira deste profissional (ex.: dermato 180d). Vazio = usa o da clínica.', null=True, verbose_name='Janela de paciente ativo (dias)'),
        ),
    ]
