# Generated by Django 5.2.12 on 2026-07-20 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0004_practitioner_active_window_days'),
        ('tenants', '0002_clinic_active_window_days_alter_clinic_ehr_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='careunit',
            name='address',
            field=models.JSONField(blank=True, default=dict, verbose_name='Endereço'),
        ),
        migrations.AddField(
            model_name='careunit',
            name='work_journey',
            field=models.JSONField(blank=True, default=list, help_text='Janelas de atendimento da unidade (workJourney do EHR): [{"startDate", "endDate", "rRule", "available"}...] - alimenta a sugestão de dias no form de agendamento.', verbose_name='Disponibilidade'),
        ),
        migrations.AlterField(
            model_name='careunit',
            name='external_id',
            field=models.CharField(blank=True, max_length=32, verbose_name='ID no EHR'),
        ),
        migrations.AlterField(
            model_name='insurancecompany',
            name='external_id',
            field=models.CharField(blank=True, max_length=32, verbose_name='ID no EHR'),
        ),
        migrations.AlterField(
            model_name='insuranceplan',
            name='external_id',
            field=models.CharField(blank=True, max_length=32, verbose_name='ID no EHR'),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='external_id',
            field=models.CharField(blank=True, max_length=32, verbose_name='ID no EHR'),
        ),
        migrations.CreateModel(
            name='PractitionerProcedure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deletado em')),
                ('duration_min', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Duração (min)')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Preço')),
                ('allow_online', models.BooleanField(default=False, verbose_name='Agenda online')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)ss', to='tenants.clinic', verbose_name='Clínica')),
                ('practitioner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offered_procedures', to='scheduling.practitioner', verbose_name='Profissional')),
                ('procedure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practitioner_offers', to='scheduling.procedure', verbose_name='Procedimento')),
            ],
            options={
                'verbose_name': 'Procedimento do profissional',
                'verbose_name_plural': 'Procedimentos dos profissionais',
                'constraints': [models.UniqueConstraint(fields=('practitioner', 'procedure'), name='uniq_practitioner_procedure')],
            },
        ),
    ]
