# Generated by Django 5.2.12 on 2026-07-20 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0005_careunit_address_careunit_work_journey_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='comments_html',
            field=models.TextField(blank=True, help_text='HTML sanitizado - vai no `comments` do EHR.', verbose_name='Observações'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Preenchido do procedimento do profissional; editável no form.', max_digits=10, null=True, verbose_name='Preço'),
        ),
        migrations.AddField(
            model_name='practitionerprocedure',
            name='comments',
            field=models.TextField(blank=True, help_text='Instruções pós-agendamento.', verbose_name='Orientações'),
        ),
        migrations.AddField(
            model_name='practitionerprocedure',
            name='description',
            field=models.TextField(blank=True, help_text='HTML sanitizado do EHR.', verbose_name='Descrição'),
        ),
    ]
