# Generated by Django 5.2.12 on 2026-07-21 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0006_appointment_comments_html_appointment_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Agendada'), ('confirmed', 'Confirmada'), ('waiting', 'Aguardando atendimento'), ('in_progress', 'Em atendimento'), ('completed', 'Realizada'), ('no_show', 'Faltou'), ('canceled', 'Cancelada')], default='scheduled', max_length=15, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='ehrstatusmap',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Agendada'), ('confirmed', 'Confirmada'), ('waiting', 'Aguardando atendimento'), ('in_progress', 'Em atendimento'), ('completed', 'Realizada'), ('no_show', 'Faltou'), ('canceled', 'Cancelada')], max_length=15, verbose_name='Status normalizado'),
        ),
    ]
