# Generated by Django 5.2.12 on 2026-07-09 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deletado em')),
                ('wa_id', models.CharField(help_text="E.164 sem '+' (formato Meta).", max_length=20, verbose_name='Número (wa_id)')),
                ('display_name', models.CharField(blank=True, max_length=160, verbose_name='Nome no WhatsApp')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)ss', to='tenants.clinic', verbose_name='Clínica')),
            ],
            options={
                'verbose_name': 'Contato',
                'verbose_name_plural': 'Contatos',
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deletado em')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('cpf', models.CharField(blank=True, db_index=True, max_length=14, verbose_name='CPF')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Nascimento')),
                ('gender', models.CharField(choices=[('unknown', 'Não informado'), ('male', 'Masculino'), ('female', 'Feminino')], default='unknown', max_length=10, verbose_name='Gênero')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, db_index=True, help_text='E.164 — vincula o Contact do WhatsApp.', max_length=20, verbose_name='Telefone')),
                ('city', models.CharField(blank=True, max_length=120, verbose_name='Cidade')),
                ('state', models.CharField(blank=True, max_length=2, verbose_name='UF')),
                ('address', models.JSONField(blank=True, default=dict, verbose_name='Endereço')),
                ('profession', models.CharField(blank=True, max_length=120, verbose_name='Profissão')),
                ('comments_html', models.TextField(blank=True, help_text='HTML sanitizado na entrada (whitelist).', verbose_name='Observações')),
                ('insurance_name', models.CharField(blank=True, max_length=120, verbose_name='Convênio (texto)')),
                ('source', models.CharField(choices=[('local', 'Cadastrado aqui'), ('ehr', 'Importado do EHR')], default='local', max_length=10, verbose_name='Origem')),
                ('external_id', models.CharField(blank=True, max_length=64, verbose_name='ID no EHR')),
                ('raw_payload', models.JSONField(blank=True, default=dict, verbose_name='Payload cru')),
                ('last_appointment_at', models.DateTimeField(blank=True, db_index=True, help_text='Denormalizado da agenda — deriva o status ativo/inativo/reativar.', null=True, verbose_name='Última consulta')),
                ('sync_status', models.CharField(choices=[('synced', 'Sincronizado'), ('pending', 'Aguardando sincronização'), ('failed', 'Falha na sincronização')], default='synced', max_length=10, verbose_name='Sincronização')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)ss', to='tenants.clinic', verbose_name='Clínica')),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
            },
        ),
        migrations.CreateModel(
            name='PatientContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deletado em')),
                ('is_primary', models.BooleanField(default=False, help_text='Desambiguação do Inbox: a quem o número pertence por padrão.', verbose_name='Paciente principal')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_contacts', to='patients.contact', verbose_name='Contato')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_contacts', to='patients.patient', verbose_name='Paciente')),
            ],
            options={
                'verbose_name': 'Vínculo contato-paciente',
                'verbose_name_plural': 'Vínculos contato-paciente',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deletado em')),
                ('name', models.CharField(max_length=120, verbose_name='Nome')),
                ('color', models.CharField(default='#149AA1', max_length=7, verbose_name='Cor')),
                ('external_id', models.CharField(blank=True, max_length=32, verbose_name='ID no EHR')),
                ('identifier', models.DecimalField(blank=True, decimal_places=0, help_text='Bit da tag no EHR — os valores chegam a 2^62.', max_digits=20, null=True, verbose_name='Identifier (bitmask)')),
                ('sync_scope', models.CharField(choices=[('synced', 'Sincronizada com o EHR'), ('pending_push', 'Aguardando criação no EHR'), ('local_only', 'Somente local')], default='synced', max_length=15, verbose_name='Escopo de sync')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)ss', to='tenants.clinic', verbose_name='Clínica')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
            },
        ),
        migrations.CreateModel(
            name='PatientTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deletado em')),
                ('origin', models.CharField(choices=[('ehr', 'EHR'), ('local', 'Local')], help_text='O diff do pull só cria/remove atribuições origin=EHR.', max_length=10, verbose_name='Origem')),
                ('sync_status', models.CharField(choices=[('synced', 'Sincronizado'), ('pending', 'Aguardando sincronização'), ('failed', 'Falha na sincronização')], default='synced', max_length=10, verbose_name='Sincronização')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_tags', to='patients.patient', verbose_name='Paciente')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='patients.tag', verbose_name='Tag')),
            ],
            options={
                'verbose_name': 'Tag do paciente',
                'verbose_name_plural': 'Tags dos pacientes',
            },
        ),
        migrations.AddConstraint(
            model_name='contact',
            constraint=models.UniqueConstraint(fields=('clinic', 'wa_id'), name='uniq_contact_wa_id'),
        ),
        migrations.AddConstraint(
            model_name='patient',
            constraint=models.UniqueConstraint(condition=models.Q(('external_id', ''), _negated=True), fields=('clinic', 'external_id'), name='uniq_patient_ext'),
        ),
        migrations.AddConstraint(
            model_name='patientcontact',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('patient', 'contact'), name='uniq_patient_contact'),
        ),
        migrations.AddConstraint(
            model_name='patientcontact',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('is_primary', True)), fields=('contact',), name='uniq_primary_patient_per_contact'),
        ),
        migrations.AddConstraint(
            model_name='tag',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('clinic', 'name'), name='uniq_tag_name'),
        ),
        migrations.AddConstraint(
            model_name='patienttag',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('patient', 'tag'), name='uniq_patient_tag'),
        ),
    ]
