# Generated by Django 5.2.12 on 2026-07-09 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='identifier',
            field=models.BigIntegerField(blank=True, help_text='Bit da tag no EHR - chega a 2^62. BigInteger é exato e suficiente: a vSaúde (.NET) usa long signed de 64 bits, teto em 2^62.', null=True, verbose_name='Identifier (bitmask)'),
        ),
    ]
