# Generated by Django 5.2.12 on 2026-07-09 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_alter_tag_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='cpf',
            field=models.CharField(blank=True, db_index=True, help_text='personalIdentifier do EHR — pode ser CPF, DNI ou passaporte.', max_length=32, verbose_name='Documento (CPF)'),
        ),
    ]
