# Generated by Django 5.2.12 on 2026-07-09 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_alter_patient_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='last_appointment_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Denormalizado da agenda — deriva o status ativo/inativo (90 dias).', null=True, verbose_name='Última consulta'),
        ),
    ]
