# Generated by Django 5.2.12 on 2026-07-11 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_alter_patient_last_appointment_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='next_appointment_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Denormalizado da agenda — próxima consulta futura (não cancelada). Um retorno agendado mantém o paciente ativo, sem viés de reativação.', null=True, verbose_name='Próxima consulta'),
        ),
    ]
