# Generated by Django 5.2.12 on 2026-07-20 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0006_backfill_next_appointment_at'),
        ('scheduling', '0005_careunit_address_careunit_work_journey_and_more'),
        ('tenants', '0003_clinic_ehr_push_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='birth_info',
            field=models.JSONField(blank=True, default=dict, help_text='Pediatria: idade gestacional, peso/altura ao nascer, perímetro cefálico, ordem.', verbose_name='Dados do nascimento'),
        ),
        migrations.AddField(
            model_name='patient',
            name='blood_type',
            field=models.CharField(blank=True, max_length=3, verbose_name='Tipo sanguíneo'),
        ),
        migrations.AddField(
            model_name='patient',
            name='emergency_contacts',
            field=models.JSONField(blank=True, default=list, verbose_name='Contatos de emergência'),
        ),
        migrations.AddField(
            model_name='patient',
            name='guardians',
            field=models.JSONField(blank=True, default=dict, help_text='{"mother": {"name", "phone"}, "father": ..., "partner": ..., "sponsor": ...}', verbose_name='Responsáveis'),
        ),
        migrations.AddField(
            model_name='patient',
            name='height_cm',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Altura (cm)'),
        ),
        migrations.AddField(
            model_name='patient',
            name='weight_kg',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Peso (kg)'),
        ),
        migrations.CreateModel(
            name='ClinicalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deletado em')),
                ('kind', models.CharField(choices=[('note', 'Nota'), ('prescription', 'Prescrição'), ('exam', 'Exame'), ('form_response', 'Formulário')], max_length=15, verbose_name='Tipo')),
                ('origin', models.CharField(choices=[('ehr', 'EHR (espelho)'), ('local', 'Local')], default='local', max_length=8, verbose_name='Origem')),
                ('date', models.DateTimeField(db_index=True, verbose_name='Data')),
                ('text', models.TextField(blank=True, help_text='HTML sanitizado - texto da nota ou conteúdo da prescrição local.', verbose_name='Conteúdo')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Título')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('document_url', models.URLField(blank=True, help_text='Link do EHR (prescrição/exame) - visualização autenticada.', max_length=500, verbose_name='Documento')),
                ('form_answers', models.JSONField(blank=True, default=list, help_text='[{"label", "answer", "answerValue", "fieldType", ...}]', verbose_name='Respostas do formulário')),
                ('creator_name', models.CharField(blank=True, max_length=200, verbose_name='Autor (nome)')),
                ('creator_license', models.CharField(blank=True, max_length=120, verbose_name='Autor (registro)')),
                ('source', models.CharField(blank=True, help_text='record | examination (EHR); vazio = local.', max_length=20, verbose_name='Fonte')),
                ('external_id', models.CharField(blank=True, max_length=64, verbose_name='ID no EHR')),
                ('raw_payload', models.JSONField(blank=True, default=dict, verbose_name='Payload cru')),
                ('sync_status', models.CharField(choices=[('synced', 'Sincronizado'), ('pending', 'Aguardando sincronização'), ('failed', 'Falha na sincronização')], default='synced', max_length=10, verbose_name='Sincronização')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)ss', to='tenants.clinic', verbose_name='Clínica')),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clinical_entries', to='patients.patient', verbose_name='Paciente')),
                ('practitioner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clinical_entries', to='scheduling.practitioner', verbose_name='Profissional')),
            ],
            options={
                'verbose_name': 'Registro clínico',
                'verbose_name_plural': 'Registros clínicos',
                'indexes': [models.Index(fields=['patient', '-date'], name='patients_cl_patient_4b045e_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('external_id', ''), _negated=True), fields=('clinic', 'source', 'external_id'), name='uniq_clinical_entry_ext')],
            },
        ),
        migrations.CreateModel(
            name='PrescriptionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deletado em')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('content', models.TextField(blank=True, help_text='HTML sanitizado.', verbose_name='Conteúdo')),
                ('hint', models.TextField(blank=True, verbose_name='Instruções')),
                ('medications', models.JSONField(blank=True, default=list, verbose_name='Medicações')),
                ('smart', models.BooleanField(default=False, verbose_name='Smart')),
                ('special_prescription', models.BooleanField(default=False, verbose_name='Receita especial')),
                ('origin', models.CharField(choices=[('ehr', 'EHR (espelho)'), ('local', 'Local')], default='local', max_length=8, verbose_name='Origem')),
                ('external_id', models.CharField(blank=True, max_length=64, verbose_name='ID no EHR')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)ss', to='tenants.clinic', verbose_name='Clínica')),
            ],
            options={
                'verbose_name': 'Modelo de prescrição',
                'verbose_name_plural': 'Modelos de prescrição',
                'constraints': [models.UniqueConstraint(condition=models.Q(('external_id', ''), _negated=True), fields=('clinic', 'external_id'), name='uniq_prescription_model_ext')],
            },
        ),
    ]
