# Generated by Django 5.2.12 on 2026-07-29 13:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0007_patient_birth_info_patient_blood_type_and_more'),
        ('tenants', '0004_clinic_appointments_backfilled_until'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deletado em')),
                ('body', models.TextField(verbose_name='Anotação')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_notes', to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)ss', to='tenants.clinic', verbose_name='Clínica')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='patients.contact', verbose_name='Contato')),
            ],
            options={
                'verbose_name': 'Nota do contato',
                'verbose_name_plural': 'Notas do contato',
                'ordering': ['-created_at'],
            },
        ),
    ]
