# Generated by Django 5.2.12 on 2026-07-30 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0009_contact_unicidade_entre_vivos'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='clinical_synced_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text="Quando o prontuário deste paciente foi lido do EHR pela última vez. Nulo = NUNCA conferido, que é diferente de 'não tem nada'. É o que permite dizer honestamente o quanto de um período já foi coberto (RF-PAR-4) e o que a conferência escolhe primeiro.", null=True, verbose_name='Prontuário conferido em'),
        ),
    ]
