# Generated by Django 5.2.12 on 2026-07-31 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0010_patient_clinical_synced_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='clinical_synced_at',
        ),
    ]
