# Generated by Django 5.2.12 on 2026-08-13 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0011_remove_patient_clinical_synced_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='marketing_opt_out',
            field=models.BooleanField(default=False, help_text='RF-SEQ-8. Sai do botão nativo da Meta nos modelos de marketing (webhook `user_preferences`) ou da mão da equipe. O pedido é do NÚMERO: se dois pacientes usam o mesmo aparelho, a casa pediu para parar. Barra sequência de marketing e modelo MARKETING; confirmação de consulta continua saindo.', verbose_name='Pediu para não receber promoções'),
        ),
    ]
